from waveshare_epd import epd7in5_V2
import math
import requests
import json
from urllib.request import urlopen
import pytz # timezone
import datetime
import locale
locale.setlocale(locale.LC_TIME,'')
import time

BEGIN_DAY = 8
END_DAY = 20
DAYS = 2
TIMEZONE = 'Europe/Paris'
ALLDAY_MAX = 2

timezone = pytz.timezone(TIMEZONE)
basetime = datetime.datetime.now(timezone)
basetime.astimezone(timezone)
now = datetime.datetime.today()
start = basetime.replace(hour=BEGIN_DAY,minute=0)
print(now)

end = start + datetime.timedelta(days=DAYS)

token = ' Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IjFSNE5fQXRXYU5Hd0hPa1BfcUtRTVdxajZwengwRk96T0pud052UEFJUjQiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wN2U5YjZhNC02ZTlkLTQ1N2ItOWU5OC04MzZhNjVmYmMwOWEvIiwiaWF0IjoxNjE5Nzg1ODcxLCJuYmYiOjE2MTk3ODU4NzEsImV4cCI6MTYxOTc4OTc3MSwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zb2Z0OnJlcTIiLCJ1cm46bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiQVNRQTIvOFRBQUFBRTFnQVFLZ1o5SDNveDVHbnp3ODJJZU85amdMenNZMEpFOEFrbHZrYWN2MD0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIGV4cGxvcmVyIChvZmZpY2lhbCBzaXRlKSIsImFwcGlkIjoiZGU4YmM4YjUtZDlmOS00OGIxLWE4YWQtYjc0OGRhNzI1MDY0IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJQRVJFSVJBIiwiZ2l2ZW5fbmFtZSI6IktldmluIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiOTIuMTcwLjIxNC4yMTIiLCJuYW1lIjoiUEVSRUlSQSBLZXZpbiIsIm9pZCI6IjA3ZDQxNzExLWZjZDktNGZiYS04NDE5LTUwNDQ4ZDc1NDExZCIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS04NjE1Njc1MDEtNTA3OTIxNDA1LTE5NTc5OTQ0ODgtNDMxMTQiLCJwbGF0ZiI6IjUiLCJwdWlkIjoiMTAwMzIwMDA5NDVDM0E4RCIsInJoIjoiMC5BWE1BcExicEI1MXVlMFdlbUlOcVpmdkFtclhJaTk3NTJiRklxSzIzU05weVVHUnpBTHMuIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWRXcml0ZSBvcGVuaWQgcHJvZmlsZSBTZWN1cml0eUV2ZW50cy5SZWFkLkFsbCBTZWN1cml0eUV2ZW50cy5SZWFkV3JpdGUuQWxsIFVzZXIuUmVhZCBVc2VyLlJlYWRCYXNpYy5BbGwgVXNlci5SZWFkV3JpdGUgZW1haWwiLCJzdWIiOiIwdjF6bVVCb3lpb3R5cmFpdlhaR0l2T0hvTGtaMUMtYlByUXNlazNhNGpnIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkVVIiwidGlkIjoiMDdlOWI2YTQtNmU5ZC00NTdiLTllOTgtODM2YTY1ZmJjMDlhIiwidW5pcXVlX25hbWUiOiJrZXZpbi5wZXJlaXJhQGluZm90ZWwuY29tIiwidXBuIjoia2V2aW4ucGVyZWlyYUBpbmZvdGVsLmNvbSIsInV0aSI6IndIaTVrbFNudkVhT19sc2IwaUFsQVEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfc3QiOnsic3ViIjoiLW16TmpPZWVZaVd1R3RGb2toXzhpT2ZVbk5ZRk5DTk00cWxCV2M5b3NiMCJ9LCJ4bXNfdGNkdCI6MTQ4NzMyNjQzMn0.L0lKhLn38CEpqJdgiQBLS0a7HB6Cm3teL77kbNUUodQp4hvQQ3K1VWRZ8olQh78EvCgvwdGMbeoE9o1ZLJY3YE2WUb2TkE9wE7FhFK1WDa7v86B9wDhgxUBLuemNuXRvK3qBWoBkq4GJtoWqtZAL3vG-ZLYZV2r18A_uavM7VRV_TybidBFMLHt3Jth7iwppEVO0Hpi7HmFXilRqLAVmP36IuRRS_Nap8jXU8M_OjwLFzx_SsBHFblw4wCnzTqvWGzeL8ebeTS0wxJOfKe8AWYei5rorkjgvUU9whuL_0NXoxeMeDZVveDKdO6eZlrVQk7gBoqYUBuYR2w6bODH-Jw'
header = {
    'prefer': 'outlook.timezone=\"Europe/Paris\"',
    'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IjVTdlNMNkpGODlIUVdEOTN5WDYybG9HRmx4MjJ3ZXJlRU1YS1FUQnFFdm8iLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wN2U5YjZhNC02ZTlkLTQ1N2ItOWU5OC04MzZhNjVmYmMwOWEvIiwiaWF0IjoxNjE5NzkwOTI2LCJuYmYiOjE2MTk3OTA5MjYsImV4cCI6MTYxOTc5NDgyNiwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zb2Z0OnJlcTIiLCJ1cm46bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiQVNRQTIvOFRBQUFBcUxONlVad2RWZWYwdzMvTHd3SnZTRE52Sy9hUTZXLzNhYkd3a0d2VmV0cz0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIGV4cGxvcmVyIChvZmZpY2lhbCBzaXRlKSIsImFwcGlkIjoiZGU4YmM4YjUtZDlmOS00OGIxLWE4YWQtYjc0OGRhNzI1MDY0IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJQRVJFSVJBIiwiZ2l2ZW5fbmFtZSI6IktldmluIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiOTIuMTcwLjIxNC4yMTIiLCJuYW1lIjoiUEVSRUlSQSBLZXZpbiIsIm9pZCI6IjA3ZDQxNzExLWZjZDktNGZiYS04NDE5LTUwNDQ4ZDc1NDExZCIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS04NjE1Njc1MDEtNTA3OTIxNDA1LTE5NTc5OTQ0ODgtNDMxMTQiLCJwbGF0ZiI6IjUiLCJwdWlkIjoiMTAwMzIwMDA5NDVDM0E4RCIsInJoIjoiMC5BWE1BcExicEI1MXVlMFdlbUlOcVpmdkFtclhJaTk3NTJiRklxSzIzU05weVVHUnpBTHMuIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWRXcml0ZSBvcGVuaWQgcHJvZmlsZSBTZWN1cml0eUV2ZW50cy5SZWFkLkFsbCBTZWN1cml0eUV2ZW50cy5SZWFkV3JpdGUuQWxsIFVzZXIuUmVhZCBVc2VyLlJlYWRCYXNpYy5BbGwgVXNlci5SZWFkV3JpdGUgZW1haWwiLCJzdWIiOiIwdjF6bVVCb3lpb3R5cmFpdlhaR0l2T0hvTGtaMUMtYlByUXNlazNhNGpnIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkVVIiwidGlkIjoiMDdlOWI2YTQtNmU5ZC00NTdiLTllOTgtODM2YTY1ZmJjMDlhIiwidW5pcXVlX25hbWUiOiJrZXZpbi5wZXJlaXJhQGluZm90ZWwuY29tIiwidXBuIjoia2V2aW4ucGVyZWlyYUBpbmZvdGVsLmNvbSIsInV0aSI6IjdWT1g2UGpHaDAtTERMWHE2TnNhQVEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfc3QiOnsic3ViIjoiLW16TmpPZWVZaVd1R3RGb2toXzhpT2ZVbk5ZRk5DTk00cWxCV2M5b3NiMCJ9LCJ4bXNfdGNkdCI6MTQ4NzMyNjQzMn0.UfW9XwnPdonMoXmjwGpm7NxKjtf5Wm69VF0JSIVhsohOOh_ou6MIEIWkZk-zqgkNd2aGoHMIu9GjN8_r5yxV252FVKfKQSdsT3tErBUped2SqwlI2GSZ7dmGlQ9ClPbDeo190IitZJ9dLNSdskDbAda3_UpmmIHKrlsPa47UH2laipnjB0RnnPeGPUL6aqch-JfTZ1DIgATjNOs-N7N4w0BSld8NEd2Z4kTwEJJiuuB_SQeXl67lv4kB9taKTsa8Gm7YRZoJ3xw3pCFMGEhNeFGKAeEJ6GIUxIklKi_z8WBs6QltTANCRl2KA-TybmIeI4wr2_W_6Y2gisG-bDCWJQ'


 }


query_params = {
    'startDateTime': start,
    'endDateTime': end,
    '$select': 'subject,organizer,start,end',
    '$orderby': 'start/dateTime',
    #'$top': '50',
  }



#myUrl = "https://graph.microsoft.com/v1.0/me/events?$select=subject,organizer,start,end"
myUrl = "https://graph.microsoft.com/v1.0/me/calendarview"
#URLS =  ["https://graph.microsoft.com/v1.0/me/events?$select=subject,organizer,start,end,location"]


response = requests.get(myUrl, headers=header,params=query_params)
json_obj = response.json()
data = json_obj["value"]

print (data)



width = epd7in5_V2.EPD_WIDTH
height = epd7in5_V2.EPD_HEIGHT

offset_top =0 
offset_left =360
bar_top = 20
bar_left = 20
allday_size = 15
offset_allday = ALLDAY_MAX * allday_size
hours_day = END_DAY - BEGIN_DAY
per_hour = math.floor((height - bar_top - offset_top - offset_allday) / hours_day)
per_day = math.floor((width - bar_left - offset_left) / DAYS)

headline_size = 15
text_size = 12
